CREATE TABLE blpt_tbl (
    id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    goal TEXT NOT NULL,
    desc TEXT NOT NULL,
    start_dt BIGINT NOT NULL,
    end_dt BIGINT NOT NULL,
    ctime BIGINT NOT NULL,
    mtime BIGINT NOT NULL
);
